### ISSUE TITLE
Не создавать deposit intention на суммы меньше минималок

### ISSUE THREAD

**Issue by c0gnize** [bitzlato/peatio#120]
![Screenshot 2021-09-09 at 15 54 04](https://user-images.githubusercontent.com/12247182/132689405-c1f98c6a-f512-4892-89d0-380711544b76.png)
Создал депозит на сумму 0.00000010, при этом `deposits/intention` нормально это воспринял

Нужно запрещать на уровне валидация создавать такие deposits intention у которых сумма меньше минимален указанной в currency

**Comment by dapi** [comment]
Надо запретить принимать deposit/intention с суммами меньше минималок. Откидывать их на уровне валидации. со стороны фронта должна быть уже поддержка для этого

**Comment by dapi** [comment]
intention не очень удачное название для модели, на самом деле это invoice. Человек создает invoice который сам же оплачивает через p2p. Можно зарефакторить и переименовать intention в invoice, поддержав это с фронта.

**Comment by c0gnize** [comment]
https://github.com/bitzlato/baseapp/issues/10
