### ISSUE TITLE
Неконсистентность `created_at` поля в `trade`

### ISSUE THREAD

**Issue by aleksxor** [bitzlato/peatio#188]
Поле `created_at` возвращается как строка содержащая кол-во секунд. В документации описана как строка в iso8601. Большинство (это неточно) других ресурсов возвращают такие поля как, действительно, дату в формате iso8601.

**Comment by aleksxor** [comment]
Даже ещё интереснее. Если я пытаюсь получить данные из публичного эндпоинта `/markets/{market}/trades` то там `created_at` идут как секунды. если же я пытаюсь получить из `/account/trades` то там идёт iso8601

**Comment by dapi** [comment]
Это где она так возвращается? Через вебсокет или только в API?
