### ISSUE TITLE
Расчёт estimated values и заменить ETH на BTC

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#3]
![Screen Shot 2021-06-17 at 15 52 14](https://user-images.githubusercontent.com/31139/122400093-1206cb80-cf84-11eb-9441-ce8413aabeda.png)

**Comment by PapevisO** [comment]
Не понял, пока.
Уточни контекст где отрисовывается сабж.
Если поле USD ненулевое должно ли поле BTC отображать оценочную стоимость?

**Comment by dapi** [comment]
https://market.bitzlato.bz/wallets в шапке

**Comment by dapi** [comment]
![Screen Shot 2021-08-18 at 19 32 56](https://user-images.githubusercontent.com/31139/129936799-ac4a78ee-2930-4b32-95f0-1fe83695493f.png)
