### ISSUE TITLE
при добавлении нового адреса, resend отрабатывает, но по факту письмо с новым кодом не приходит на почту. а с первоначальным pin-ом уже не подтверждает.

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#34]
![photo_2021-08-04 16 51 10](https://user-images.githubusercontent.com/31139/128192752-35f84242-00ce-44e3-8a4d-34bcd88c5f58.jpeg)

**Comment by radanisk** [comment]
https://github.com/bitzlato/barong/pull/13
