### ISSUE TITLE
rake-задача по удалению рынка

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#7]
Не знаю, может такая уже есть. Нам нужна таскан которая удаляет указанный рынок, а именно:
1) Все deposits
2) Все withdraws
3) Все операции
4) Пользовательские балансы
5) Саму запись в market помечает как отключенную.
6) Может что еще забыл?

**Comment by PapevisO** [comment]
Есть две проблемы:

Я не вижу прямых ассоциаций между моделями:
Market -> has -> Deposits
Market -> has -> Withdraws
Market -> has -> Accounts

Правильно ли я понял что под рынком понимется Currency плюс все Markets где она Base или Quote элемент пары?

Я не советую практиковать прибивание Orders и/или Trades. Это создает массу проблем в будущем, включая но не ограничиваясь:
- Orders ассоциированные с Trades на миллион записей будут несколько случайно неприбитых, это способствует дополнительным проблемам, об этом ниже.
- Когда число записей начнет доходить до миллиона и выше, появятся проблемы удаления давних Orders и Trades, которые могут занимать столько времени (из-за потерь на индексацию) что транзакция БД просто фейлится и делает Rollback. Возможно в какой-то из свежих Mariadb этот аспект не выражен или менее выражен, но это нужно проверить прежде чем начинать практиковать.
- RabbitMQ становится совсем плохо когда у него в пуле начинают зависать Ordera не примаппленные к Market и/или к Trade, я наблюдал как графики длин очередей в rabbitmq dashboard монотонно росли и достигали миллионов в таких случаях. Приходилось поставить Shovel плагин чтобы их массово прибивать без необходимости перезапуска RabbitMQ со стиранием всех его данных.

Для того чтобы всё-таки прекращать хранение ненужных более Orders и Trades, более беспроблемный вариант - создать новую таблицу с Orders и Trades не содержащие записей подлежащих удалению, после этого остановить биржу на maintenance на сколько-то минут, каскадно прибить живую таблицу с индексом, переименовать временные таблицы в постоянные и асинхронно добавить индексы.

**Comment by dapi** [comment]
Да, удалять надо и рынок и монеты. В частности у нас это был рынок bbb/uuu.

> Я не вижу прямых ассоциаций между моделями:
> Market -> has -> Deposits
> Market -> has -> Withdraws
> Market -> has -> Accounts

Через валюты. Торговли между убиваемыми валютами и оставшимися не было.

Рынок закрыт. В rabbitmq по этому рынку пусто.

Нужно просто грохнуть все записи по этим валютам и рынку.  Это безопасно в нашем случае.

**Comment by dapi** [comment]
В личку кину дамп базы. Учти что удалять надо малыми пачками по 100 записей,  чтобы база не встала. ПОэтому надо в консоли отображать прогресс.
