### ISSUE TITLE
Обновления таблицы ордеров на фронте в реальном времени

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#8]
Проблема. На фронте человек создал сделку. Она висит в таблице ордеров. Когда сделка исполнена из таблицы ордеров не уходит.

**Comment by dapi** [comment]
Каждый пункт отдельный PR

**Comment by c0gnize** [comment]
А обновление списка депозитов и списаний в реальном времени (bitzlato/baseapp#9) в рамках этой задачи будет ?

**Comment by dapi** [comment]
Нет, надо отдельно делать. Обновление сделок достаточно серьезная задача, ее лучше отдельно.
