### ISSUE TITLE
Исправить схему swagger

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#93]
https://validator.swagger.io/validator/debug?url=https%3A%2F%2Fmarket.bitzlato.com%2Fapi%2Fv2%2Fpeatio%2Fswagger

 swagger-схема от peatio приходит не валидная и валидтор об этом сигналит https://market.bitzlato.com/swagger/ внизу варнитн

**Comment by WergSerg** [comment]
сообщение выдает вот этих модулях:
 
"attribute paths.'/api/v2/peatio/public/trading_fees'(get).[market_type].default is not of type `string`",
    "attribute paths.'/api/v2/peatio/public/markets'(get).[type].default is not of type `string`",
    "attribute paths.'/api/v2/peatio/market/trades'(get).[market_type].default is not of type `string`",
    "attribute paths.'/api/v2/peatio/market/orders/cancel'(post).[market_type].default is not of type `string`",
    "attribute paths.'/api/v2/peatio/market/orders'(get).[market_type].default is not of type `string`",****

**Comment by dapi** [comment]
https://github.com/bitzlato/peatio/pull/110
