### ISSUE TITLE
Проверять наличие public_name перед созданием бенефициара из фронта

### ISSUE THREAD

**Issue by dapi** [bitzlato/peatio#98]
![Screen Shot 2021-09-02 at 15 41 36](https://user-images.githubusercontent.com/31139/131845501-bb341d5a-a7d4-43c1-9ff2-4926eebcc3ea.png)

p2p.user_profile.public_name or p2p.user_profile.generated_name

**Comment by dapi** [comment]
![Uploading photo_2021-09-03 16.20.55.jpeg…]()

**Comment by dapi** [comment]
В бенефициарах добавить вариацию адреса

**Comment by dapi** [comment]
user_profile.public_name

**Comment by temacxz** [comment]
Сегодня попробовать добить проверку по БД bitzlato (см barong), если не успею, то закрывать таск на текущем фунцкионале (проверка по регуляркам)
